http:
  port: "8081"
  
sfdc:
  username: "your_username"
  password: "your_password"
  token: "your_token"
  
file:
  accountsDir: "C:/Users/BoyuanZhang/Desktop/MUFundamentals4.1_studentFiles_22sept2018/resources"
  
db:
  host: "mudb.learn.mulesoft.com"
  port: "3306"
  user: "mule"
  password: "mule"
  database: "training"